Repository InventoryBox/InventoryBox_Android, pull requests merged in 2020-07, with the labels that each got.

#7 3-graph baseLayout : 상단 캘린더 뷰 완성
  .gradle/6.1.1/executionHistory/executionHistory.bin
  .gradle/6.1.1/executionHistory/executionHistory.lock
  .gradle/6.1.1/fileHashes/fileHashes.bin
  .gradle/6.1.1/fileHashes/fileHashes.lock
  .gradle/6.1.1/fileHashes/resourceHashesCache.bin
  .gradle/6.1.1/javaCompile/classAnalysis.bin
  .gradle/6.1.1/javaCompile/jarAnalysis.bin
  .gradle/6.1.1/javaCompile/javaCompile.lock
  .gradle/6.1.1/javaCompile/taskHistory.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .idea/assetWizardSettings.xml
  .idea/caches/build_file_checksums.ser
  .idea/modules/app/app.iml
  app/src/main/java/com/example/inventorybox/Adpater/GraphCalendarAdapter.kt
  app/src/main/java/com/example/inventorybox/Adpater/MainPagerAdapter.kt
  app/src/main/java/com/example/inventorybox/fragment/GraphFragment.kt
  app/src/main/res/drawable/graph_rec_grey.xml
  app/src/main/res/drawable/graph_rec_selected.xml
  app/src/main/res/drawable/graph_rec_white.xml
  app/src/main/res/font/lotte_font_family.xml
  app/src/main/res/font/lotte_happy_bold.ttf
  app/src/main/res/font/lotte_happy_light.ttf
  app/src/main/res/font/lotte_happy_medium.ttf
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/layout/item_graph_calendar.xml
Labels: Andriod, 가영, 재고량추이

#14 8 graph category
  .gradle/6.1.1/executionHistory/executionHistory.bin
  .gradle/6.1.1/executionHistory/executionHistory.lock
  .gradle/6.1.1/fileHashes/fileHashes.bin
  .gradle/6.1.1/fileHashes/fileHashes.lock
  .gradle/6.1.1/fileHashes/resourceHashesCache.bin
  .gradle/6.1.1/javaCompile/classAnalysis.bin
  .gradle/6.1.1/javaCompile/jarAnalysis.bin
  .gradle/6.1.1/javaCompile/javaCompile.lock
  .gradle/6.1.1/javaCompile/taskHistory.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .idea/caches/build_file_checksums.ser
  .idea/libraries/Gradle__com_github_amarjain07_StickyScrollView_1_0_2_aar.xml
  .idea/modules/app/app.iml
  app/src/main/java/com/example/inventorybox/Adpater/GraphCalendarAdapter.kt
  app/src/main/java/com/example/inventorybox/Adpater/GraphCategoryRVAdapter.kt
  app/src/main/java/com/example/inventorybox/fragment/GraphFragment.kt
  app/src/main/res/drawable/graph_rec13_yellow.xml
  app/src/main/res/drawable/graph_rec20_dark_grey.xml
  app/src/main/res/drawable/graph_rec20_grey_blank.xml
  app/src/main/res/drawable/graph_rec9_grey.xml
  app/src/main/res/drawable/graph_rec9_white.xml
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/layout/item_graph_category.xml
  app/src/main/res/values/colors.xml
  local.properties
Labels: Andriod, 가영, 재고량추이

#16 15-graph_cur_graph 단일 그래프 추가
  .gradle/6.1.1/executionHistory/executionHistory.bin
  .gradle/6.1.1/executionHistory/executionHistory.lock
  .gradle/6.1.1/fileHashes/fileHashes.bin
  .gradle/6.1.1/fileHashes/fileHashes.lock
  .gradle/6.1.1/fileHashes/resourceHashesCache.bin
  .gradle/6.1.1/javaCompile/classAnalysis.bin
  .gradle/6.1.1/javaCompile/jarAnalysis.bin
  .gradle/6.1.1/javaCompile/javaCompile.lock
  .gradle/6.1.1/javaCompile/taskHistory.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .idea/caches/build_file_checksums.ser
  .idea/libraries/Gradle__com_github_PhilJay_MPAndroidChart_v3_1_0_aar.xml
  .idea/modules/app/app.iml
  app/build.gradle
  app/drawable-hdpi/data_ic_milk.png
  app/drawable-mdpi/data_ic_milk.png
  app/drawable-xhdpi/data_ic_milk.png
  app/drawable-xxhdpi/data_ic_milk.png
  app/drawable-xxxhdpi/data_ic_milk.png
  app/src/main/java/com/example/inventorybox/Data/GraphSingleData.kt
  app/src/main/java/com/example/inventorybox/adapter/GraphCalendarAdapter.kt
  app/src/main/java/com/example/inventorybox/adapter/GraphCategoryRVAdapter.kt
  app/src/main/java/com/example/inventorybox/adapter/GraphSingleGraphAdapter.kt
  app/src/main/java/com/example/inventorybox/adapter/HomeOrderAdapter.kt
  app/src/main/java/com/example/inventorybox/adapter/HomeTodayOrderData.kt
  app/src/main/java/com/example/inventorybox/adapter/MainPagerAdapter.kt
  app/src/main/java/com/example/inventorybox/fragment/GraphFragment.kt
  app/src/main/java/com/example/inventorybox/fragment/HomeFragment.kt
  app/src/main/java/com/example/inventorybox/getColorFromRes.kt
  app/src/main/java/com/example/inventorybox/graph/CustomBarDataSet.kt
  app/src/main/java/com/example/inventorybox/graph/RoundedChartRenderer.kt
  app/src/main/java/com/example/inventorybox/graph/drawSingleGraph.kt
  app/src/main/res/drawable-hdpi/data_ic_coffee.png
  app/src/main/res/drawable-hdpi/data_ic_milk.png
  app/src/main/res/drawable-mdpi/data_ic_coffee.png
  app/src/main/res/drawable-mdpi/data_ic_milk.png
  app/src/main/res/drawable-xhdpi/data_ic_coffee.png
  app/src/main/res/drawable-xhdpi/data_ic_milk.png
  app/src/main/res/drawable-xxhdpi/data_ic_coffee.png
  app/src/main/res/drawable-xxhdpi/data_ic_milk.png
  app/src/main/res/drawable-xxxhdpi/data_ic_coffee.png
  app/src/main/res/drawable-xxxhdpi/data_ic_milk.png
  app/src/main/res/drawable/graph_rec9_middlegrey_blank.xml
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/layout/item_graph_main_graph.xml
  app/src/main/res/values/strings.xml
  drawable-hdpi/data_ic_milk.png
  drawable-mdpi/data_ic_milk.png
  drawable-xhdpi/data_ic_milk.png
  drawable-xxhdpi/data_ic_milk.png
  drawable-xxxhdpi/data_ic_milk.png
Labels: Andriod, 가영, 재고량추이

#17 15 graph cur graph
  .gradle/6.1.1/executionHistory/executionHistory.bin
  .gradle/6.1.1/executionHistory/executionHistory.lock
  .gradle/6.1.1/fileHashes/fileHashes.bin
  .gradle/6.1.1/fileHashes/fileHashes.lock
  .gradle/6.1.1/fileHashes/resourceHashesCache.bin
  .gradle/6.1.1/javaCompile/classAnalysis.bin
  .gradle/6.1.1/javaCompile/jarAnalysis.bin
  .gradle/6.1.1/javaCompile/javaCompile.lock
  .gradle/6.1.1/javaCompile/taskHistory.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .idea/modules/app/app.iml
  app/src/main/java/com/example/inventorybox/fragment/GraphFragment.kt
  app/src/main/java/com/example/inventorybox/graph/drawSingleGraph.kt
  app/src/main/res/drawable-hdpi/data_ic_cup.png
  app/src/main/res/drawable-mdpi/data_ic_cup.png
  app/src/main/res/drawable-xhdpi/data_ic_cup.png
  app/src/main/res/drawable-xxhdpi/data_ic_cup.png
  app/src/main/res/drawable-xxxhdpi/data_ic_cup.png
  app/src/main/res/layout/fragment_graph.xml
Labels: Andriod, 가영, 재고량추이

#19 18 graph float btn
  .gradle/6.1.1/executionHistory/executionHistory.bin
  .gradle/6.1.1/executionHistory/executionHistory.lock
  .gradle/6.1.1/fileHashes/fileHashes.bin
  .gradle/6.1.1/fileHashes/fileHashes.lock
  .gradle/6.1.1/fileHashes/resourceHashesCache.bin
  .gradle/6.1.1/javaCompile/classAnalysis.bin
  .gradle/6.1.1/javaCompile/jarAnalysis.bin
  .gradle/6.1.1/javaCompile/javaCompile.lock
  .gradle/6.1.1/javaCompile/taskHistory.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  app/src/main/java/com/example/inventorybox/fragment/GraphFragment.kt
  app/src/main/java/com/example/inventorybox/graph/drawDoubleGraph.kt
  app/src/main/res/drawable-hdpi/icon.png
  app/src/main/res/drawable-mdpi/icon.png
  app/src/main/res/drawable-xhdpi/icon.png
  app/src/main/res/drawable-xxhdpi/icon.png
  app/src/main/res/drawable-xxxhdpi/icon.png
  app/src/main/res/layout/fragment_graph.xml
Labels: Andriod, 가영, 재고량추이

#36 30-Exchange : baseLayout
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/inventorybox/activity/MainActivity.kt
  app/src/main/java/com/example/inventorybox/adapter/ExchangeRVAdapter.kt
  app/src/main/java/com/example/inventorybox/adapter/GraphSingleGraphAdapter.kt
  app/src/main/java/com/example/inventorybox/adapter/HomeOrderAdapter.kt
  app/src/main/java/com/example/inventorybox/data/ExchangeData.kt
  app/src/main/java/com/example/inventorybox/fragment/ExchangeAllFragment.kt
  app/src/main/java/com/example/inventorybox/fragment/ExchangeFoodFragment.kt
  app/src/main/java/com/example/inventorybox/fragment/ExchangeFragment.kt
  app/src/main/java/com/example/inventorybox/fragment/ExchangeProductFragment.kt
  app/src/main/java/com/example/inventorybox/fragment/ExchangeRecentFragment.kt
  app/src/main/java/com/example/inventorybox/fragment/HomeFragment.kt
  app/src/main/java/com/example/inventorybox/fragment/HomeOrderEditFragment.kt
  app/src/main/res/drawable-hdpi/exchange_ic_location.png
  app/src/main/res/drawable-hdpi/exchangemain_btn_heart.png
  app/src/main/res/drawable-hdpi/exchangemain_btn_heart_unchecked.png
  app/src/main/res/drawable-hdpi/exchangemain_btn_my.png
  app/src/main/res/drawable-hdpi/exchangemain_btn_plus.png
  app/src/main/res/drawable-hdpi/exchangemain_ic_search.png
  app/src/main/res/drawable-mdpi/exchange_ic_location.png
  app/src/main/res/drawable-mdpi/exchangemain_btn_heart.png
  app/src/main/res/drawable-mdpi/exchangemain_btn_heart_unchecked.png
  app/src/main/res/drawable-mdpi/exchangemain_btn_my.png
  app/src/main/res/drawable-mdpi/exchangemain_btn_plus.png
  app/src/main/res/drawable-mdpi/exchangemain_ic_search.png
  app/src/main/res/drawable-xhdpi/exchange_ic_location.png
  app/src/main/res/drawable-xhdpi/exchangemain_btn_heart.png
  app/src/main/res/drawable-xhdpi/exchangemain_btn_heart_unchecked.png
  app/src/main/res/drawable-xhdpi/exchangemain_btn_my.png
  app/src/main/res/drawable-xhdpi/exchangemain_btn_plus.png
  app/src/main/res/drawable-xhdpi/exchangemain_ic_search.png
  app/src/main/res/drawable-xxhdpi/exchange_ic_location.png
  app/src/main/res/drawable-xxhdpi/exchangemain_btn_heart.png
  app/src/main/res/drawable-xxhdpi/exchangemain_btn_heart_unchecked.png
  app/src/main/res/drawable-xxhdpi/exchangemain_btn_my.png
  app/src/main/res/drawable-xxhdpi/exchangemain_btn_plus.png
  app/src/main/res/drawable-xxhdpi/exchangemain_ic_search.png
  app/src/main/res/drawable-xxxhdpi/exchange_ic_location.png
  app/src/main/res/drawable-xxxhdpi/exchangemain_btn_heart.png
  app/src/main/res/drawable-xxxhdpi/exchangemain_btn_heart_unchecked.png
  app/src/main/res/drawable-xxxhdpi/exchangemain_btn_my.png
  app/src/main/res/drawable-xxxhdpi/exchangemain_btn_plus.png
  app/src/main/res/drawable-xxxhdpi/exchangemain_ic_search.png
  app/src/main/res/drawable/exchange_btn_border.xml
  app/src/main/res/drawable/exchange_search_border.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_exchange.xml
  app/src/main/res/layout/fragment_exchange_all.xml
  app/src/main/res/layout/fragment_exchange_food.xml
  app/src/main/res/layout/fragment_exchange_product.xml
  app/src/main/res/layout/fragment_exchange_recent.xml
  app/src/main/res/layout/fragment_home_order_edit.xml
  app/src/main/res/layout/item_exchange.xml
Labels: Andriod, 성은, 재고교환

#53 32 record stock add
  app/src/main/java/com/example/inventorybox/activity/RecordCategoryActivity.kt
  app/src/main/java/com/example/inventorybox/activity/RecordRecordActivity.kt
  app/src/main/res/layout/activity_category_edit.xml
  app/src/main/res/layout/activity_record.xml
Labels: Andriod, 재고기록, 화진

#56 32-RecordStockAdd
  app/src/main/java/com/example/inventorybox/activity/RecordAddActivity.kt
  app/src/main/java/com/example/inventorybox/activity/RecordCategoryActivity.kt
  app/src/main/java/com/example/inventorybox/activity/RecordIconActivity.kt
  app/src/main/java/com/example/inventorybox/activity/RecordRecordActivity.kt
  app/src/main/java/com/example/inventorybox/etc/RecordDatePicker.kt
  app/src/main/java/com/example/inventorybox/fragment/RecordFragment.kt
  app/src/main/res/layout/activity_icon_setting.xml
  app/src/main/res/layout/record_datepicker.xml
Labels: Andriod, 재고기록, 화진

#57 37-home : 체크박스, 그래프 추가
  app/build.gradle
  app/src/main/java/com/example/inventorybox/adapter/HomeOrderAdapter.kt
  app/src/main/java/com/example/inventorybox/data/Graph5DaysData.kt
  app/src/main/java/com/example/inventorybox/fragment/HomeFragment.kt
  app/src/main/java/com/example/inventorybox/graph/draw5DaysGraph.kt
  app/src/main/res/layout/fragment_exchange.xml
  app/src/main/res/layout/item_home_edit_memo.xml
  app/src/main/res/layout/item_home_orderlist.xml
Labels: Andriod, 성은, 홈화면

#59 56 home edit
  app/src/main/java/com/example/inventorybox/activity/MainActivity.kt
  app/src/main/java/com/example/inventorybox/etc/CustomDialog.kt
  app/src/main/java/com/example/inventorybox/fragment/GraphDetail.kt
  app/src/main/java/com/example/inventorybox/graph/draw5DaysGraph.kt
  app/src/main/res/drawable/graph_rec16_whitegrey.xml
  app/src/main/res/layout/layout_custom_dialog.xml
Labels: Andriod, 가영, 홈화면

#61 37-home : 햄버거 완료
  app/src/main/java/com/example/inventorybox/activity/HomeSettingsActivity.kt
  app/src/main/java/com/example/inventorybox/activity/MainActivity.kt
  app/src/main/java/com/example/inventorybox/adapter/HomeOrderAdapter.kt
  app/src/main/java/com/example/inventorybox/adapter/MainPagerAdapter.kt
  app/src/main/java/com/example/inventorybox/fragment/ExchangeAllFragment.kt
  app/src/main/java/com/example/inventorybox/fragment/HomeFragment.kt
  app/src/main/res/layout/activity_home_settings.xml
  app/src/main/res/layout/fragment_exchange_all.xml
Labels: Andriod, 성은, 홈화면

#75 74-login : 로그인, 회원가입 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/inventorybox/SignUp.kt
  app/src/main/java/com/example/inventorybox/activity/LoginActivity.kt
  app/src/main/java/com/example/inventorybox/activity/SignUpPersonalActivity.kt
  app/src/main/java/com/example/inventorybox/activity/SignUpProfileActivity.kt
  app/src/main/java/com/example/inventorybox/activity/SignUpTermsActivity.kt
  app/src/main/java/com/example/inventorybox/fragment/HomeFragment.kt
  app/src/main/java/com/example/inventorybox/network/GET/GetHomeOrderResponse.kt
  app/src/main/java/com/example/inventorybox/network/NetworkService.kt
  app/src/main/java/com/example/inventorybox/network/custonEnqueue.kt
  app/src/main/res/drawable-hdpi/id_btn_back.png
  app/src/main/res/drawable-hdpi/login_top_line.png
  app/src/main/res/drawable-hdpi/profile_btn_regist.png
  app/src/main/res/drawable-hdpi/profile_shape.png
  app/src/main/res/drawable-hdpi/terms_all_check_unselected.png
  app/src/main/res/drawable-hdpi/terms_ic_notice.png
  app/src/main/res/drawable-mdpi/id_btn_back.png
  app/src/main/res/drawable-mdpi/login_top_line.png
  app/src/main/res/drawable-mdpi/profile_btn_regist.png
  app/src/main/res/drawable-mdpi/profile_shape.png
  app/src/main/res/drawable-mdpi/terms_all_check_unselected.png
  app/src/main/res/drawable-mdpi/terms_ic_notice.png
  app/src/main/res/drawable-xhdpi/id_btn_back.png
  app/src/main/res/drawable-xhdpi/login_top_line.png
  app/src/main/res/drawable-xhdpi/profile_btn_regist.png
  app/src/main/res/drawable-xhdpi/profile_shape.png
  app/src/main/res/drawable-xhdpi/terms_all_check_unselected.png
  app/src/main/res/drawable-xhdpi/terms_ic_notice.png
  app/src/main/res/drawable-xxhdpi/id_btn_back.png
  app/src/main/res/drawable-xxhdpi/login_top_line.png
  app/src/main/res/drawable-xxhdpi/profile_btn_regist.png
  app/src/main/res/drawable-xxhdpi/profile_shape.png
  app/src/main/res/drawable-xxhdpi/terms_all_check_unselected.png
  app/src/main/res/drawable-xxhdpi/terms_ic_notice.png
  app/src/main/res/drawable-xxxhdpi/id_btn_back.png
  app/src/main/res/drawable-xxxhdpi/login_top_line.png
  app/src/main/res/drawable-xxxhdpi/profile_btn_regist.png
  app/src/main/res/drawable-xxxhdpi/profile_shape.png
  app/src/main/res/drawable-xxxhdpi/terms_all_check_unselected.png
  app/src/main/res/drawable-xxxhdpi/terms_ic_notice.png
  app/src/main/res/drawable/signup_btn_middlegrey.xml
  app/src/main/res/drawable/signup_btn_yellow.xml
  app/src/main/res/drawable/signup_et_grey_border.xml
  app/src/main/res/drawable/signup_profile_circle.xml
  app/src/main/res/drawable/signup_profile_et_backgrond.xml
  app/src/main/res/drawable/signup_terms_underline.xml
  app/src/main/res/drawable/underline_grey.xml
  app/src/main/res/drawable/underline_red.xml
  app/src/main/res/drawable/underline_yellow.xml
  app/src/main/res/drawable/yellow_border.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up_personal.xml
  app/src/main/res/layout/activity_sign_up_profile.xml
  app/src/main/res/layout/activity_sign_up_terms.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_edit_memo.xml
Labels: Andriod, 로그인, 성은, 회원가입

#76 73 record category checkbox
  app/src/main/java/com/example/inventorybox/activity/RecordCategoryActivity.kt
  app/src/main/res/layout/activity_category_edit.xml
Labels: Andriod, 재고기록, 화진

#88 73 record category checkbox
  app/src/main/java/com/example/inventorybox/activity/RecordCategoryActivity.kt
  app/src/main/java/com/example/inventorybox/activity/RecordRecordActivity.kt
  app/src/main/java/com/example/inventorybox/adapter/RecordCategoryAdapter.kt
  app/src/main/java/com/example/inventorybox/adapter/RecordCategoryEditAdapter.kt
  app/src/main/java/com/example/inventorybox/fragment/RecordFragment.kt
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_record_completedlist.xml
  app/src/main/res/layout/layout_add_custom_dialog.xml
  app/src/main/res/values/styles.xml
Labels: Andriod, 재고기록, 화진
